version: "2"
services:
  redis:
    image: redis:3.2.6
    ports:
      - 127.0.0.1:6379:6379
  localstack:
    image: atlassianlabs/localstack
    ports:
      - 127.0.0.1:4567-4582:4567-4582
      - 127.0.0.1:8080:8080
    environment:
      - SERVICES=s3:4572
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
